open Printf
open Insideout_ast

let escape s =
  let buf = Buffer.create (2 * String.length s) in
  for i = 0 to String.length s - 1 do
    match s.[i] with
    | '$' -> Buffer.add_string buf "\\$"
    | '\\' -> Buffer.add_string buf "\\\\"
    | c -> Buffer.add_char buf c
  done;
  Buffer.contents buf

let emit_ocaml_common ~custom_esc ~source ~opens ~params oc l =
  fprintf oc "(* Generated by insideout from %s. Do not edit. *)\n" source;

  List.iter (fun module_ ->
    fprintf oc "open %s;;\n" module_
  ) opens;

  List.iter (fun (ident, opt_default) ->
    match opt_default with
    | None -> ()
    | Some default -> fprintf oc "let default_%s = %S\n" ident default
  ) params;

  (* Call custom escape function (e.g. html_escape) over
     each expanded variable. *)
  match custom_esc with
  | None ->
      ()
  | Some function_source ->
      fprintf oc "let _esc = %s\n;;\n" function_source

let emit_ocaml_expanders ~expand_function_name ~source ~esc ~params oc l =
  let args_no_defaults =
    let l =
      List.map (fun (ident, opt_default) ->
        "\n  ~" ^ ident
      ) params
    in
    String.concat "" l
  in
  fprintf oc "\
let %s%s () =

  String.concat \"\" [\n"
    expand_function_name
    args_no_defaults;
  List.iter (function
    | Var x ->
        let id = x.ident in
        let expanded_var =
          match x.format with
          | None ->
              id
          | Some fmt ->
              sprintf "Printf.sprintf %S %s" fmt id
        in
        fprintf oc "    %s;\n"
          (if x.esc then esc expanded_var else expanded_var)

    | Text s ->
        fprintf oc "    %S;\n" s
  ) l;
  fprintf oc "  ]\n\n";

  let args_with_defaults =
    let l =
      List.map (fun (ident, opt_default) ->
        match opt_default with
        | Some default ->
            sprintf "\n  ?(%s = default_%s)" ident ident
        | _ ->
            "\n  ~" ^ ident
      ) params
    in
    String.concat "" l
  in

  fprintf oc "\
let preview%s () =
  %s%s ()
"
    args_with_defaults
    expand_function_name
    args_no_defaults

let emit_ocaml
    ~custom_esc ~defaults ~opens
    ~expand_function_name
    ~source
    oc l =

  let params =
    List.sort
      (fun (a, _) (b, _) -> String.compare a b)
      (Hashtbl.fold (fun k v acc -> (k, v) :: acc) defaults [])
  in
  let esc =
    match custom_esc with
    | None ->
        (fun s -> s)
    | Some function_source ->
        (fun s -> sprintf "_esc (%s)" s)
  in

  emit_ocaml_common ~custom_esc ~source ~opens ~params oc l;
  emit_ocaml_expanders ~expand_function_name ~esc ~source ~params oc l

let hashtbl_get tbl k =
  try Some (Hashtbl.find tbl k)
  with Not_found -> None

let expand_defaults ~defaults ~esc oc l =
  List.iter (function
    | Var x ->
        let id = x.ident in
        (match hashtbl_get defaults id with
         | None (* implicit variable *)
         | Some None (* explicit, no default *) ->
             let opt_format =
               match x.format with
                 None -> ""
               | Some s -> " " ^ s
             in
             fprintf oc "$%s{%s%s}" (if x.esc then "" else "$") id opt_format
         | Some (Some s) ->
             output_string oc (if esc then escape s else s)
        )
    | Text s ->
        output_string oc (if esc then escape s else s)
  ) l

let ocaml
    ~custom_esc ~opens ~expand_function_name ~source
    ic oc =
  let defaults, l = Insideout_lexer.parse_template source ic oc in
  emit_ocaml
    ~custom_esc ~defaults ~opens
    ~expand_function_name
    ~source oc l

let preview ~esc source ic oc =
  let defaults, l = Insideout_lexer.parse_template source ic oc in
  expand_defaults ~defaults ~esc oc l

let escape_html = "fun s ->
  let buf = Buffer.create (String.length s + 10) in
  String.iter (function
    | '&' -> Buffer.add_string buf \"&amp;\"
    | '<' -> Buffer.add_string buf \"&lt;\"
    | '>' -> Buffer.add_string buf \"&gt;\"
    | '\\'' -> Buffer.add_string buf \"&apos;\"
    | '\"' -> Buffer.add_string buf \"&quot;\"
    | c -> Buffer.add_char buf c
  ) s;
  Buffer.contents buf
"
